#!/bin/bash

if [ -z "$1" ]; then
	echo "No arguments provided!"
	exit 1
fi

git pull
mkdir $1
cd $1
cp ../README.md .
cp ../commit .
mkdir copywork
cd copywork
git clone https://github.com/nihad1213/holbertonschool-web_back_end
cd holbertonschool-web_back_end
cd $1
mv * ../../../
cd ../../../
rm -rf copywork
./commit
